# Generated by Django 5.1.7 on 2025-03-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('father_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('company_inn', models.IntegerField(verbose_name='ИНН организации')),
                ('person_email', models.EmailField(max_length=50, verbose_name='Email для связи')),
                ('person_phone', models.CharField(max_length=50, verbose_name='Контактный телефон')),
                ('company_related_manager', models.CharField(choices=[('Маркаров Иван', 'Markarov'), ('Гарцуев Александр', 'Gartsuev')], verbose_name='Менеджер партнера')),
            ],
            options={
                'verbose_name': 'Зарегистрированный партнер',
                'verbose_name_plural': 'Зарегистрированные партнеры',
                'ordering': ['company_inn'],
            },
        ),
    ]
