# Generated by Django 5.1.7 on 2025-03-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='company_inn',
            field=models.CharField(max_length=50, verbose_name='ИНН организации'),
        ),
    ]
