# Generated by Django 5.1.7 on 2025-03-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_registration', '0002_alter_person_company_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_phone',
            field=models.CharField(max_length=50, unique=True, verbose_name='Контактный телефон'),
        ),
    ]
