# Generated by Django 5.1.7 on 2025-03-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_registration', '0003_alter_person_person_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='company_name',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Название организации'),
        ),
    ]
