# Generated by Django 5.1.7 on 2025-04-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_registration', '0004_person_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_unique_key',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='Уникальный ключ клиента'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='company_related_manager',
            field=models.CharField(choices=[('MARKAROV', 'Маркаров Иван'), ('GARTSUEV', 'Гарцуев Александр')], verbose_name='Менеджер партнера'),
        ),
    ]
