# Generated by Django 5.1.7 on 2025-04-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_registration', '0005_person_person_unique_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_unique_key',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Уникальный ключ клиента'),
        ),
    ]
