# Generated by Django 5.1.7 on 2025-04-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_registration', '0006_alter_person_person_unique_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='company_related_manager',
            field=models.CharField(choices=[('Маркаров Иван', 'Маркаров Иван'), ('Гарцуев Александр', 'Гарцуев Александр')], verbose_name='Менеджер партнера'),
        ),
    ]
